# Generated by Django 3.2.9 on 2022-02-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido_personalizado',
            options={'verbose_name': 'pedido personalizado', 'verbose_name_plural': 'pedidos_personalizados'},
        ),
        migrations.AlterModelOptions(
            name='servicio_personalizado',
            options={'verbose_name': 'servicio personalizado', 'verbose_name_plural': 'servicios_personalizados'},
        ),
        migrations.AlterModelOptions(
            name='tipo_servicio',
            options={'verbose_name': 'tipo de servicio', 'verbose_name_plural': 'tipo_servicios'},
        ),
    ]
