# Generated by Django 3.2.9 on 2022-01-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['id_catalogo', 'servicio_id', 'fecha_creacion', 'fecha_actualizacion', 'estado'], 'verbose_name': 'catalogo'},
        ),
    ]
