# Generated by Django 3.2.9 on 2022-03-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_auto_20220218_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_personalizado',
            name='img_servicio',
            field=models.ImageField(upload_to='Ventas/servicios_personalizados', verbose_name='Imagen del Servicio'),
        ),
    ]
