# Generated by Django 3.2.9 on 2022-03-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_servicio_personalizado_img_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_personalizado',
            name='tipo_servicio_id',
            field=models.ForeignKey(db_column='tipo_servicio_id', on_delete=django.db.models.deletion.CASCADE, to='Ventas.tipo_servicio', verbose_name='Tipo de Servicio'),
        ),
    ]
