# Generated by Django 3.2.9 on 2022-03-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_servicio_personalizado_img_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='servicio_id',
            field=models.ForeignKey(blank=True, db_column='servicio_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Ventas.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio_personalizado',
            name='tipo_servicio_id',
            field=models.ForeignKey(db_column='tipo_servicio_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='Ventas.tipo_servicio', verbose_name='Tipo de Servicio'),
            preserve_default=False,
        ),
    ]
