# Generated by Django 3.2.9 on 2022-03-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_alter_servicio_personalizado_tipo_servicio_id'),
        ('Ventas', '0004_auto_20220306_2203'),
    ]

    operations = [
    ]
