# Generated by Django 3.2.8 on 2022-02-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=250)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.BooleanField()),
                ('permisos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuracion.permisos')),
            ],
        ),
    ]
