# Generated by Django 3.2.9 on 2022-02-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0002_auto_20220215_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='id_permiso',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
