# Generated by Django 3.2.9 on 2022-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0003_alter_permiso_id_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='cambios',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Color_Letra', models.CharField(max_length=20)),
                ('Color_Fondo', models.CharField(max_length=20)),
                ('Sangria_Letra', models.CharField(max_length=20)),
                ('tamano_letra', models.CharField(max_length=20)),
                ('Tipo_Letra', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Cambios',
            },
        ),
    ]
