# Generated by Django 3.2.9 on 2022-02-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0004_cambios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cambios',
            old_name='id_rol',
            new_name='id_cambios',
        ),
    ]
