# Generated by Django 3.2.8 on 2022-02-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='permiso_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cod_postal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='img_usuario',
            field=models.ImageField(blank=True, default='perfil/profile.jpg', max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen De Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tipodocumento'),
        ),
    ]
