# Generated by Django 3.2.9 on 2022-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20220303_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistasDiarias',
            fields=[
                ('id_dia', models.AutoField(primary_key=True, serialize=False)),
                ('Contador', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
