# Generated by Django 3.2.9 on 2022-03-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_vistasdiarias'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vistasdiarias',
            table='VisitasDiarias',
        ),
    ]
