# Generated by Django 3.2.9 on 2022-03-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_img_usuario'),
        ('Usuarios', '0004_alter_vistasdiarias_table'),
    ]

    operations = [
    ]
