# Generated by Django 3.2.9 on 2022-03-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compra',
            table='Compra',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='Proveedor',
        ),
        migrations.AlterModelTable(
            name='tipo_producto',
            table='Tipo_producto',
        ),
    ]
