# Generated by Django 3.2.9 on 2022-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0002_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
