# Generated by Django 3.2.9 on 2022-03-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0003_tipo_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_producto',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
