# Generated by Django 3.2.9 on 2022-03-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0004_alter_tipo_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_producto',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
