# Generated by Django 3.2.9 on 2022-03-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0005_alter_tipo_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, db_column='tipo_producto_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Modulo_compras.tipo_producto', verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='tipo_producto',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
