# Generated by Django 3.2.9 on 2022-03-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0007_auto_20220313_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['id_compras'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total',
        ),
    ]
