# Generated by Django 3.2.7 on 2022-01-16 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_municipio', models.TextField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
                'db_table': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('permiso_id', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_documento', models.TextField()),
            ],
            options={
                'verbose_name': 'tipo_documento',
                'verbose_name_plural': 'tipos_documentos',
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('apodo', models.TextField()),
                ('telefono', models.TextField(blank=True, null=True)),
                ('celular', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('fec_nac', models.DateField()),
                ('num_documento', models.TextField()),
                ('img_usuario', models.TextField(blank=True, null=True)),
                ('contrasena', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('cod_postal', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('municipio_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.municipio')),
                ('rol_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.rol')),
                ('tipo_documento_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.tipodocumento')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.usuario')),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificiaciones',
                'db_table': 'notificaciones',
            },
        ),
    ]
