# Generated by Django 3.2.7 on 2022-01-14 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField()),
                ('servicio_id', models.IntegerField()),
                ('servicio_personalizado_id', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compras', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('proveedor_id', models.IntegerField()),
                ('precio', models.FloatField()),
                ('estado', models.IntegerField()),
                ('id_proveedores', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='FrontEnd',
            fields=[
                ('id_frond_end', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('camp1', models.CharField(max_length=1000)),
                ('camp2', models.CharField(blank=True, max_length=1000, null=True)),
                ('camp3', models.CharField(blank=True, max_length=1000, null=True)),
                ('camp4', models.CharField(blank=True, max_length=1000, null=True)),
                ('camp5', models.CharField(blank=True, max_length=1000, null=True)),
                ('camp6', models.CharField(blank=True, max_length=1000, null=True)),
                ('img1', models.CharField(blank=True, max_length=1000, null=True)),
                ('img2', models.CharField(blank=True, max_length=1000, null=True)),
                ('color_titulo', models.CharField(blank=True, max_length=11, null=True)),
                ('color_txt', models.CharField(blank=True, max_length=11, null=True)),
                ('negrita_titulo', models.TextField(blank=True, null=True)),
                ('boton_tex_compra', models.CharField(blank=True, max_length=11, null=True)),
                ('negrita_producto', models.TextField(blank=True, null=True)),
                ('tamano_texto', models.IntegerField(blank=True, null=True)),
                ('tamano_titulo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'front_end',
                'verbose_name_plural': 'front_end',
                'db_table': 'front_end',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipios', models.AutoField(primary_key=True, serialize=False)),
                ('nom_municipio', models.TextField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificiaciones',
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cita_id', models.IntegerField()),
                ('total_pagar', models.FloatField()),
                ('fecha_cita', models.DateTimeField()),
                ('descricpion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_productos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('proveedor_id', models.IntegerField()),
                ('tipo_producto_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('encargado', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('permiso_id', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('img_servicios', models.TextField()),
                ('precio', models.IntegerField()),
                ('tipo_servicio_id', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='ServicioPersonalizado',
            fields=[
                ('id_servicio_personalizado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('img_servicios', models.TextField()),
                ('tipo_servicio_id', models.IntegerField()),
                ('cita_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'servicio_personalizado',
                'verbose_name_plural': 'servicios_personalizados',
                'db_table': 'servicios_personalizados',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_documetos', models.TextField()),
            ],
            options={
                'verbose_name': 'tipo_documento',
                'verbose_name_plural': 'tipos_documentos',
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'tipo_producto',
                'verbose_name_plural': 'tipo_producto',
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'tipo_servicio',
                'verbose_name_plural': 'tipo_servicios',
                'db_table': 'tipo_servicios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('apodo', models.TextField()),
                ('telefono', models.TextField(blank=True, null=True)),
                ('celular', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('fec_nac', models.DateField()),
                ('num_documento', models.TextField()),
                ('img_usuario', models.TextField(blank=True, null=True)),
                ('contrasena', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('cod_postal', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('municipio_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.municipio')),
                ('rol_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.rol')),
                ('tipo_documento_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.tipodocumento')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.usuario')),
            ],
        ),
    ]
