# Generated by Django 3.2.7 on 2022-01-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='nom_tipo_documetos',
            new_name='nom_tipo_documento',
        ),
    ]
