# Generated by Django 3.2.7 on 2022-01-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloUsuarios', '0002_rename_nom_tipo_documetos_tipodocumento_nom_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='id_municipios',
            new_name='id_municipio',
        ),
    ]
