# Generated by Django 3.2.7 on 2022-01-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloUsuarios', '0003_rename_id_municipios_municipio_id_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'municipio', 'verbose_name_plural': 'municipios'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'notificacion', 'verbose_name_plural': 'notificiaciones'},
        ),
        migrations.AlterModelTable(
            name='municipio',
            table='municipios',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones',
        ),
    ]
